name: contract_risk_analyzer
description: "A Flutter app to analyze contract risks and costs."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.5.1

  # Utilities
  uuid: ^4.4.0

  # Database
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.21
  path_provider: ^2.1.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  drift_dev: ^2.15.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
